
jira:
  site: "http://jira.tgac.bbsrc.ac.uk"
  username: "tgacpap"
  password: "dff0LmqWKDgysG0RsIBFUgZrnsJfiMK9dqpzlhMcqSjj1uron9B0zZX70mv"

miso:
  site: "http://miso.tgac.ac.uk"
  username: "leggettr"
  pub_key: "bGVnZ2V0dHI6OntTSEF9dm5iZjNTNHc1dDAzSVhZWTRFQTg5YVJWcHNVPQ"
  # user = "tgacpap"
  # key = b"ZGF2ZXk6OjU4MmRmYzdlZTlmMTBhMWExNDA0MzMyMzU0Mjk3NjVhMGUzYTc2Mjg"

paths:

  # Directory that contain the results of the PAP after the transfer procedure has been executed
  default_dest_dir_internal_projects: "/tgac/data/reads"
  default_dest_dir_external_projects: "/tgac/data/private_reads"

  # Default directory under which PAP output is placed
  default_pap_dir: "/tgac/pnp/qc"

  # Default directory under which all raw sequencing data is placed
  default_raw_dir: "/tgac/pnp/raw"

  # Default directory where all analysis will be sent during transfer
  default_stats_dir: "/tgac/workarea/group-pb/pap_stats/data"


analysis:

  # Percentage of samples specified in the samplesheet that must be present for the analysis stage to go ahead.
  # If the user wishes to override this behaviour they can force analysis with the --"force_analysis" command line option.
  required_files_perc: 90

  # Maximum number of reads for each sample's subsample.  This should be more than will be used by centrifuge and FastQ Screen
  subsample_count: 2000000


centrifuge:

  # Adapters for bbduk
  adapters: "/tgac/references/databases/centrifuge/adapters.fa"

  # Centrifuge index database
  db: "/tgac/references/databases/centrifuge/nt"

  # ETE taxonomy database for centrifuge_classify script
  etetoolkit_db: "/tgac/references/databases/etetoolkit/20170928/taxa.sqlite"

  # Centrifuge mode options are {"off", "parallel", "multi"}
  mode: "multi"

  # If mode is parallel, this determines the threshold at which we switch from per sample centrifuge to a per project merged sample centrifuge
  # If mode is multi, then this determines how many samples are processed by each centrifuge-multi instance.  Therefore this effects the number of centrifuge-multi processes
  # that will be started in parallel in high sample projects.
  pp_threshold: 100

  # The number of threads centrifuge should use
  threads: 16

load:
  bcl2fastq: "source bcl2fastq-2.17.1.14"
  fastqc: "source fastqc-0.11.5"
  fastq_screen: "source fastqscreen-0.11.1"
  seqtk: "source seqtk-git20160921"
  bbduk: "source jre-8u144 && source bbmap-37.24"
  krona: "source krona-2.7"
  centrifuge: "source centrifuge-1.0.3_multi"

  # No longer necessary to source these in our environment as they should be included as git submodules to eipap
  multiqc: ""

