tools:
  bbduk: "/tgac/software/testing/bbmap/37.24/bbmap/bbduk.sh"
  bbnorm: "/tgac/software/testing/bbmap/37.24/bbmap/bbnorm.sh"
  tadpole: "/tgac/software/testing/bbmap/37.24/bbmap/tadpole.sh"
  fastqc: "/tgac/software/testing/fastqc/0.11.5/x86_64/bin/fastqc"

resources:
  bb_adapters: "/tgac/software/testing/bbmap/37.24/bbmap/resources/adapters.fa"


load:
  fastqc: "source fastqc-0.11.5"
  seqtk: "source seqtk-git20160921"
  bbmap: "source jre-8u144 && source bbmap-37.24"
  quast: "source quast-4.3"
  kat: "source kat-dev"
  busco: "source busco-3.0"
  blob_bwa: "source bwa-0.7.16a && source samtools-1.5"
  blob_blast: "source blast-2.6.0"
  blobtools: "source python_anaconda-2.5.0 && source blobtools-0.9.19 && source samtools-1.5"
  multiqc: "source multiqc-1.3_dev"
  ratt: "source ratt-dev && source emboss-6.6.0"

cmd:
  quast: "python2 /tgac/software/testing/quast/4.3/x86_64/bin/quast.py"

blob_blastdb: "/ei/public/databases/blast/ncbi/nt_20171013/nt"

multiqc_config: "/tgac/software/testing/bgrrl/0.1/src/ei_bgrrl/bgrrl/etc/multiqc_config.yaml"
