tools:
  # bbduk: "/tgac/software/testing/bbmap/38.06/bbmap/bbduk.sh"
  # bbnorm: "/tgac/software/testing/bbmap/38.06/bbmap/bbnorm.sh"
  # tadpole: "/tgac/software/testing/bbmap/38.06/bbmap/tadpole.sh"
  fastqc: "/tgac/software/testing/fastqc/0.11.5/x86_64/bin/fastqc"

resources:
  # bb_adapters: "/tgac/software/testing/bbmap/38.06/bbmap/resources/adapters.fa"
  bb_adapters: "/tgac/software/testing/bbmap/38.06/x86_64/bin/resources/adapters.fa"
  blob_blastdb: "/ei/public/databases/blast/ncbi/nt_20171013/nt"
  busco_databases: "/tgac/workarea/group-pb/BUSCO_DATABASES/odb9"
  multiqc_config: "/tgac/software/testing/bgrrl/0.1/src/ei_bgrrl/bgrrl/etc/multiqc_config.yaml"


params:
  # before 2018-02-21: ktrim=r k=21 mink=11 hdist=2 qtrim=lr trimq=3 minlen=100 maq=20 tpe tbo
  bbduk: "ktrim=r k=21 mink=7 hdist=1 qtrim=lr trimq=3 minlen=100 maq=20 tpe tbo"
  bbnorm: "target=100 min=2 prefilter"


load:
  fastqc: "source fastqc-0.11.5"
  seqtk: "source seqtk-git20160921"
  bbmap: "source jre-8u144 && source bbmap-38.06"
  quast: "source quast-4.3"
  kat: "source kat-dev"
  busco: "source busco-3.0"
  blob_bwa: "source bwa-0.7.16a && source samtools-1.5"
  blob_blast: "source blast-2.6.0"
  blobtools: "source python_anaconda-2.5.0 && source blobtools-0.9.19 && source samtools-1.5"
  multiqc: "source multiqc-1.5_ei"
  ratt: "source ratt-dev && source emboss-6.6.0"
  prokka: "source prokka-git"

cmd:
  quast: "python2 /tgac/software/testing/quast/4.3/x86_64/bin/quast.py"

misc:
  seqcentre: "EI"
  project: "" # If this is empty, it will be derived from bgrrl-commandline args (basename(dirname(current_folder)) by default)




