#!/bin/bash

source bwa-0.7.16a
source samtools-1.5

echo "ARGS: $@"

# " {input[0]} {params.outbam} {params.index} -t {threads} {params.index} {input[1]} {input[2]} &> {log}"
bwa index -p $3 $1
params=$(echo $@ | cut -f 4- -d " ")
echo "PARAMS: $params"
echo bwa mem $params
bwa mem $params | samtools view -buSh - > $2
