#!/bin/bash
module purge

# /tgac/software/testing/binutils/2.25.1/x86_64/bin/
echo "BEFORE: $PATH"
export PATH=$(echo $PATH | cut -f 9- -d :)
echo "AFTER: $PATH"

unset CPLUS_INCLUDE_PATH
unset LDFLAGS
unset MANPATH
unset CPPFLAGS
unset LD_LIBRARY_PATH
unset CPATH
unset PKG_CONFIG_PATH


source blast-2.6.0



# " -num_threads {threads} -query {input[0]} -db " + BLOB_BLASTDB + " -out {output.tsv} &> {log}"
blastn -outfmt '6 qseqid staxids bitscore std' -max_target_seqs 10 -max_hsps 1 -evalue 1e-25 $@


#BEFORE: /tgac/software/testing/bin/core/../..//jre/8u92/x86_64/bin:/tgac/software/testing/bin/../python_anaconda/4.4.0_py3_dm/x86_64/bin:/tgac/software/testing/binutils/2.25.1/x86_64/bin/:/tgac/software/testing/bin/core/../..//python_anaconda/4.4.0_py3_dm/x86_64/bin:/tgac/software/testing/bin/core/../..//make/4.1/x86_64/bin:/tgac/software/testing/binutils/2.25.1/x86_64/bin/:/tgac/software/testing/bin/core/../..//gcc/5.2.0/x86_64/bin:/tgac/software/production/bin/core/../..//hpccore/5/x86_64/bin:/tgac/software/testing/bin/core/../..//perl/5.20.1_gk/x86_64/bin:/usr/lib64/qt-3.3/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/tgac/software/production/bin:/tgac/software/production/libraries/bin:/tgac/software/testing/bin:/tgac/software/testing/libraries/bin:/opt/cis/bin:/opt/cis/help:/tgac/software/testing/tcl/8.6.4/x86_64/bin:/tgac/workarea/group-tg/users/schudomc/software/kraken:/usr/users/TGAC_ga004/schudomc/bin
#AFTER: /tgac/software/testing/bin/core/../..//perl/5.20.1_gk/x86_64/bin:/usr/lib64/qt-3.3/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/tgac/software/production/bin:/tgac/software/production/libraries/bin:/tgac/software/testing/bin:/tgac/software/testing/libraries/bin:/opt/cis/bin:/opt/cis/help:/tgac/software/testing/tcl/8.6.4/x86_64/bin:/tgac/workarea/group-tg/users/schudomc/software/kraken:/usr/users/TGAC_ga004/schudomc/bin
#blastn: /tgac/software/testing/bin/core/../..//python_anaconda/4.4.0_py3_dm/x86_64/lib/libgomp.so.1: version `GOMP_4.0' not found (required by blastn)
#blastn: /tgac/software/testing/bin/core/../..//python_anaconda/4.4.0_py3_dm/x86_64/lib/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by blastn)
#blastn: /tgac/software/testing/bin/core/../..//python_anaconda/4.4.0_py3_dm/x86_64/lib/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by blastn)
#blastn: /tgac/software/testing/bin/core/../..//python_anaconda/4.4.0_py3_dm/x86_64/lib/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by blastn)
