#!/bin/bash -e

DFASTPATH=/tgac/workarea/group-pb/schudomc_DFAST/dfast_core

# export PATH=$PATH:$PROKKAPATH/binaries/linux

# source hmmer-3.1b2
# source gnuparallel-20131122
source perl-5.20.1_gk
source gcc-5.2.0
source python_anaconda-4.4.0_py3_dm
source jre-8u92

INPUT=$2
NTHREADS=$1
LOG=$4
OUTDIR=$3

/usr/bin/time -v python "${DFASTPATH}/dfast" --cpu "${NTHREADS}" --center_name "EI" -g "${INPUT}" -o "${OUTDIR}"  --force &> "${LOG}"
