#!/bin/bash
source kat-dev

# r1=$(echo $@ | cut -f 1 -d " ")
# r2=$(echo $@ | cut -f 2 -d " ")
args=$(echo $@ | cut -f 3- -d " ")

# target=$(echo $@ | cut -f 5 -d " ")

/usr/bin/time -v kat $args <(zcat $1 $2) || touch $5

if [[ "$3" == "gcp" ]]; then
  /usr/bin/time -v kat_distanalysis.py "${5}.mx" || touch "${5}.mx.dist" > "${5}.mx.dist"
else
  /usr/bin/time -v kat_distanalysis.py "${5}" || touch "${5}.dist" > "${5}.dist"
fi
