#!/bin/bash -e

PROKKAPATH=/tgac/workarea/group-pb/schudomc_prokka/prokka

export PATH=$PATH:$PROKKAPATH/binaries/linux

# source hmmer-3.1b2
# source gnuparallel-20131122
source perl-5.20.1_gk
source jre-8u92

/usr/bin/time -v $PROKKAPATH/bin/prokka --cpus $5 --outdir $1 --prefix $2 --centre EI $3 --force &> $4


# sbatch -p ei-medium --mem 8GB -c 8 <(echo '#!/bin/bash'$'\n'"export PATH=\$PATH:../schudomc_prokka/prokka/binaries/linux; source hmmer-3.1b2 && source gnuparallel-20131122 && source perl-5.20.1_gk && source jre-8u92 && /tgac/workarea/group-pb/schudomc_prokka/prokka/bin/prokka --cpus 8 --outdir prokka_test --prefix eco_test --centre EI eco_frags.fa --force")
