#!/bin/bash -e

source reapr-1.0.18

# INPUT
# OUTPUT
assembly=$1
outdir=$2
in_r1=$3
in_r2=$4
threads=$5

#sample=$(basename $(dirname $assembly))
#destdir=$reapr_outdir/$sample
mkdir -p $outdir/input

reapr_in=$outdir/input/$(basename $input .fasta).reapr_in.fasta
reapr facheck $assembly $reapr_in

reapr_bam=$outdir/input/long_mapped.bam

reapr smaltmap -n $threads $reapr_in $in_r1 $in_r2 $reapr_bam
reapr pipeline $reapr_in $reapr_bam $outdir
