#!/bin/bash
source ratt-dev
source emboss-6.6.0

outdir=$1
contigs=$2
refname=$3
donefile=$4
sample=$(basename $(dirname $contigs))

prefix=${sample}_$(basename $refname)

CWD=$(pwd)
is_debug=0

echo XXX &&
cd $outdir && 
echo $(pwd) &&
# if [[ $is_debug == 0 ]]; then 
echo $RATT_HOME/start.ratt.sh $refname $contigs $prefix Strain && 
/usr/bin/time -v $RATT_HOME/start.ratt.sh $refname $contigs $prefix Strain && 
# cd .. &&
# tar czf $(basename $outdir).tar.gz $(basename $outdir) &&
# cd - &&
mkdir -p nucmer && 
mv nucmer.* nucmer/ && 
rm -rf DONUCMER.log Sequences query.* Reference.*.fasta && 
find . -maxdepth 1 -name '*.tmp2.embl' -exec rm {} \; && 
mkdir -p artemis && 
mv *.final.embl artemis/ && 
cat artemis/*.final.embl > $prefix.final.embl && 
# mv artemis/$prefix.final.embl . &&
mkdir -p artemis/not_transfered &&
mv *.NOTTransfered.embl artemis/not_transfered &&
cat artemis/not_transfered/*.NOTTransfered.embl > $prefix.not_transfered.embl &&
find . -maxdepth 1 -name '*.Report.txt' -size -167c -size +165c -type f -exec rm {} \; && 
find . -maxdepth 1 -name '*.Report.gff' -size 0 -exec rm {} \; && 
(
header=0;
for f in $(find . -maxdepth 1 -name '*.Report.txt'); do
  if [[ $header == 0 ]]; then
    head -n 1 $f | awk -v FS="\t" -v OFS="\t" '{ print Sample,Reference,$0; }';
    header=1;
  fi 
  tail -n +2 $f | awk -v FS="\t" -v OFS="\t" -v col1="$sample" -v col2="$refname" '{ print col1,col2,$0; }';
  rm $f;
done > $prefix.report.tsv
) &&
(
for f in $(find . -maxdepth 1 -name '*.Report.gff'); do
  echo "# "$(basename $f .Report.gff);
  cat $f;
  rm $f;
done > $prefix.report.gff
) && 
find . -maxdepth 1 -name '*.embl' -and -not -name '*.final.embl' -and -not -name '*.not_transfered.embl' -exec rm {} \; &&
# fi &&
rm -f *.done* &&
seqret -sequence $prefix.final.embl -outseq $prefix.final.gff -offormat gff -feature &&
head -n 1 final.gff > $prefix.final.gff &&
head -n 5 final.gff | tail -n 3 >> $prefix.final.gff &&
awk -v prefix=$prefix -v OFS="\t" -v FS="\t" '/^[^#]/ { if ($3 != "contig") { $1=gensub(".final$", "", "g", $1); $1=gensub("^"prefix".", "", "g", $1); print $0; }}' final.gff >> $prefix.final.gff &&
# rm final.gff &&

cd $CWD && 
touch $donefile
