package:
    name: bgrrl
    version: "0.6"

source:
    path: ../.git 

build:
    skip_compile_pyc:
       - "../bgrrl/zzz/*.smk.py" 

requirements:
    build:
        - "python>=3.6"
        - setuptools
    run:
        - "python>=3.6"
        - setuptools
        - "snakemake>=4.4.0"
        - "drmaa"
